// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBakeryOrderingSystem;

namespace OnlineBakeryOrderingSystem.Migrations
{
    [DbContext(typeof(BakeryContext))]
    partial class BakeryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineBakeryOrderingSystem.Bakery", b =>
                {
                    b.Property<int>("CustomerNumber")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BakeryProduct");

                    b.Property<string>("CustomerAddress");

                    b.Property<string>("CustomerBankAccountNumber");

                    b.Property<string>("CustomerEmailAddress")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("CustomerName");

                    b.Property<DateTime>("Date");

                    b.Property<decimal>("ItemPrice");

                    b.Property<int>("NumberOfOrder");

                    b.HasKey("CustomerNumber")
                        .HasName("PK_Bakeries");

                    b.ToTable("Bakeries");
                });

            modelBuilder.Entity("OnlineBakeryOrderingSystem.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerNumber");

                    b.Property<string>("Description");

                    b.Property<decimal>("Itemprice");

                    b.Property<int>("NumberOfOrder");

                    b.Property<DateTime>("TransactionDate");

                    b.Property<int>("TransactionType");

                    b.HasKey("TransactionId")
                        .HasName("PK_Transactions");

                    b.HasIndex("CustomerNumber");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("OnlineBakeryOrderingSystem.Transaction", b =>
                {
                    b.HasOne("OnlineBakeryOrderingSystem.Bakery", "Bakery")
                        .WithMany()
                        .HasForeignKey("CustomerNumber")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
